---
title: "NEO Earth Close Approaches"
output:
  pdf_document:
    # toc: true
#classoption:
#  landscape
---

```{r, include=FALSE}

library(tidyverse)
library(lubridate)
library(openxlsx)
library(stringr)
library(reshape2)
library(flextable)
library(ggthemes)

```

```{r, echo=FALSE, include=FALSE}

# https://cneos.jpl.nasa.gov/ca/
df.raw <- read.xlsx("../data/external/nasa.gov/cneos_closeapproach_data.xlsx")

```

```{r, echo=FALSE, warning=FALSE}

df <- df.raw %>%
  mutate(
    
    V.infinity.km_s = as.numeric(`V.infinity.(km/s)`),
    V.relative.km_s = `V.relative.(km/s)`,
    
    tmp = gsub("&gt;", "", `CA.Distance.Nominal.(LD.|.au)`),
    CA.Distance.Nominal.LD = as.numeric(str_trim(str_split_fixed(tmp, " | ", 3)[, 1])),
    CA.Distance.Nominal.au = as.numeric(str_trim(str_split_fixed(tmp, " | ", 3)[, 3])),
    CA.Distance.Nominal.km = CA.Distance.Nominal.au * 149597900,
    
    # tmp = gsub("&gt; ", "", `CA.Distance.Minimum.(LD.|.au)`),
    # tmp = gsub("\t", "", `CA.Distance.Minimum.(LD.|.au)`),
    # CA.Distance.Minimum.LD = as.numeric(str_trim(str_split_fixed(tmp, " | ", 3)[, 1])),
    # CA.Distance.Minimum.au = as.numeric(str_trim(str_split_fixed(tmp, " | ", 3)[, 3])),
    # CA.Distance.Minimum.km = CA.Distance.Minimum.au * 149597900,
    
    tmp = gsub("&lt;", "", `Close-Approach.(CA).Date`),
    Close.Approach.Date = ymd_hm(str_split_fixed(tmp, "±", 3)[, 1]),
    Close.Approach.Date.Err = str_split_fixed(tmp, "±", 3)[, 2],
    
    Is.Future = Close.Approach.Date >= today()
    ) %>%
  arrange(Close.Approach.Date) %>%
  mutate(
    Diameter = gsub("-", "", Diameter),
    Diameter = gsub("  ", " ", Diameter),
    Diameter = gsub("  ", " ", Diameter),
    Diameter = gsub("  ", " ", Diameter),
    Diameter.format = case_when(
      Diameter == "n/a" ~ 3,
      grepl("±", Diameter) ~ 2,
      TRUE ~ 1
      ),
    tmp1 = str_trim(str_split_fixed(Diameter, " ", 6)[, 1]),
    tmp2 = str_trim(str_split_fixed(Diameter, " ", 6)[, 2]),
    tmp3 = str_trim(str_split_fixed(Diameter, " ", 6)[, 3]),
    tmp4 = str_trim(str_split_fixed(Diameter, " ", 6)[, 4]),
    tmp5 = str_trim(str_split_fixed(Diameter, "±", 6)[, 1]),
    tmp6 = str_trim(str_split_fixed(Diameter, "±", 6)[, 2]),
    tmp7 = str_trim(str_split_fixed(tmp6, " ", 6)[, 1])
    ) %>%
  mutate(
    Diameter.min = case_when(
      Diameter.format == 1 ~ if_else(tmp2 == "km", as.numeric(tmp1) * 1000, as.numeric(tmp1)),
      Diameter.format == 2 ~ (as.numeric(tmp5) - as.numeric(tmp7)) * 1000,
      Diameter.format == 3 ~ as.numeric(tmp2)
      ),
    Diameter.max = case_when(
      Diameter.format == 1 ~ if_else(tmp4 == "km", as.numeric(tmp3) * 1000, as.numeric(tmp3)),
      Diameter.format == 2 ~ (as.numeric(tmp5) + as.numeric(tmp7)) * 1000,
      Diameter.format == 3 ~ as.numeric(tmp2)
      )
    ) %>%
  select(
    Object,
    Close.Approach.Date,
    CA.Distance.Nominal.km,
    Diameter.min,
    Diameter.max,
    V.infinity.km_s,
    V.relative.km_s,
    Is.Future
    )

write.xlsx(df, "../data/processed/neo-earth-close-approaches.xlsx")

```

```{r, echo=FALSE, warning=FALSE, fig.width=20, fig.height=12}

df_past <- df %>%
  filter(!Is.Future)

df_future <- df %>%
  filter(Is.Future)

df_highlight <- df_future %>%
  filter(CA.Distance.Nominal.km <= 100000)

df_highlight2 <- df_future %>%
  filter(Diameter.min >= 1000)

df_future %>%
  ggplot(aes(x = as.Date(Close.Approach.Date), y = CA.Distance.Nominal.km)) +
  labs(
    caption = "Source: https://cneos.jpl.nasa.gov/ca/",
    x = "Close Approach Date",
    y = "Distance (km)",
    color = "",
    size = "Diameter"
    ) +
  scale_y_continuous(label = scales::comma, trans="log10") +
  geom_vline(xintercept = today(), color = "red", alpha = .3) +
  geom_hline(yintercept = 100000, color = "red", alpha = .3) +
  geom_point(
    data = df_past,
    mapping = aes(size = Diameter.min, color = "Past"),
    # color = "grey",
    alpha = .2,
    na.rm = TRUE
    ) +
  geom_point(
    mapping = aes(size = Diameter.min, color = "Future"),
    # color = "black",
    alpha = .2,
    na.rm = TRUE
    ) +
  geom_point(
    data = df_highlight2,
    mapping = aes(size = Diameter.min, color = "Larger than 1 km"),
    # color = "blue",
    alpha = .5,
    na.rm = TRUE
    ) +
  geom_point(
    data = df_highlight,
    mapping = aes(size = Diameter.min, color = "Within 100,000 km"),
    # color = "red",
    alpha = .7,
    na.rm = TRUE
    ) +
  geom_text(
    data = df_highlight,
    mapping = aes(
      y = CA.Distance.Nominal.km, label = paste(
        "\n\n\n\n",
        Object, "\n",
        scales::comma(round(CA.Distance.Nominal.km)), "km\n",
        Close.Approach.Date
        ),
      color = "Within 100,000 km"
      ),
    # color = "red",
    size = 3,
    alpha = .7,
    na.rm = TRUE
    # , check_overlap = TRUE
    ) +
  scale_color_manual(values = c("black", "blue", "grey", "red", "purple")) +
  theme_minimal()
  # theme_wsj()
# +
#   theme(
#     axis.text.x = element_text(angle = 90, hjust = 1),
#     legend.position = "top"
#     )

```

```{r, echo=FALSE}

# ttt <- df %>%
#   filter(Is.Future) %>%
#   mutate(Is.Future = NULL) %>%
#   filter(Close.Approach.Date < today() %m+% months(10 * 12)) %>%
#   arrange(CA.Distance.Nominal.km)
# 
# ttt %>%
#   flextable() %>%
#   theme_zebra() %>%
#   autofit()

```
